output   = "service/infra/db/models"
wipe     = true
no-tests = true

[mysql]
  dbname  = "test_database"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = "root"
  sslmode = "false"
