// Code generated by MockGen. DO NOT EDIT.
// Source: service/application/app.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockApp is a mock of App interface
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
}

// MockAppMockRecorder is the mock recorder for MockApp
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// SQSWorker mocks base method
func (m *MockApp) SQSWorker(ctx context.Context, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SQSWorker", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SQSWorker indicates an expected call of SQSWorker
func (mr *MockAppMockRecorder) SQSWorker(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SQSWorker", reflect.TypeOf((*MockApp)(nil).SQSWorker), ctx, message)
}

// S3Worker mocks base method
func (m *MockApp) S3Worker(ctx context.Context, bucket, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "S3Worker", ctx, bucket, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// S3Worker indicates an expected call of S3Worker
func (mr *MockAppMockRecorder) S3Worker(ctx, bucket, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "S3Worker", reflect.TypeOf((*MockApp)(nil).S3Worker), ctx, bucket, filename)
}
